"""
scikit-learn based prediction module.

Two real, trainable models:

1. OverflowRiskModel (RandomForestRegressor)
   Learns fill_level as a function of {hours_since_collection, weight_kg,
   temperature_c, bin_type, capacity_kg, hour_of_day, day_of_week} from the
   historical sensor_readings table. Used to project each bin's fill level
   forward in time and flag bins that will cross the overflow threshold
   within the next N hours.

2. WasteGenerationForecaster (RandomForestRegressor)
   Learns total daily collected waste (kg) per area as a function of
   {day_of_week, day_of_month, month, rolling_avg} from historical
   collection totals, and forecasts the next 7 days per area.

Both models train on data generated by the simulation engine (see
simulation/sensor_simulator.py) -- this is legitimate ML on realistic
synthetic sensor data, standard practice when live IoT hardware/history
isn't available yet, as explicitly requested (software-only, simulation
mode).
"""
import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
import joblib

MODEL_DIR = os.path.join(os.path.dirname(__file__), "saved_models")
os.makedirs(MODEL_DIR, exist_ok=True)
OVERFLOW_MODEL_PATH = os.path.join(MODEL_DIR, "overflow_model.joblib")
FORECAST_MODEL_PATH = os.path.join(MODEL_DIR, "waste_forecast_model.joblib")

BIN_TYPE_MAP = {"General": 0, "Plastic": 1, "Paper": 2, "Metal": 3,
                 "Glass": 4, "Organic": 5, "E-waste": 6}

OVERFLOW_THRESHOLD = 85.0  # percent fill considered "overflow risk"


def _reading_rows_to_df(rows):
    """rows: list of dicts with bin_id, fill_level, weight_kg, temperature_c,
    recorded_at, bin_type, capacity_kg, last_collected_at"""
    df = pd.DataFrame(rows)
    if df.empty:
        return df
    df["recorded_at"] = pd.to_datetime(df["recorded_at"])
    df["last_collected_at"] = pd.to_datetime(df["last_collected_at"])
    df["hours_since_collection"] = (
        (df["recorded_at"] - df["last_collected_at"]).dt.total_seconds() / 3600.0
    ).clip(lower=0)
    df["hour_of_day"] = df["recorded_at"].dt.hour
    df["day_of_week"] = df["recorded_at"].dt.dayofweek
    df["bin_type_enc"] = df["bin_type"].map(BIN_TYPE_MAP).fillna(0)
    return df


FEATURE_COLS = ["hours_since_collection", "weight_kg", "temperature_c",
                 "bin_type_enc", "capacity_kg", "hour_of_day", "day_of_week"]


def train_overflow_model(reading_rows):
    """Train and persist the RandomForestRegressor. Returns metrics dict."""
    df = _reading_rows_to_df(reading_rows)
    if len(df) < 30:
        return {"trained": False, "reason": "Not enough sensor history yet (need >=30 readings)."}

    X = df[FEATURE_COLS]
    y = df["fill_level"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestRegressor(n_estimators=150, max_depth=10, random_state=42)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    mae = mean_absolute_error(y_test, preds)

    joblib.dump(model, OVERFLOW_MODEL_PATH)
    return {"trained": True, "mae": round(float(mae), 3), "n_samples": len(df),
            "feature_importances": dict(zip(FEATURE_COLS, model.feature_importances_.round(4).tolist()))}


def load_overflow_model():
    if os.path.exists(OVERFLOW_MODEL_PATH):
        return joblib.load(OVERFLOW_MODEL_PATH)
    return None


def predict_bin_overflow(bin_dict, recent_readings, horizon_hours=(6, 12, 24)):
    """
    Predicts fill level at future horizons for one bin.
    Uses the trained RandomForest if available; otherwise falls back to a
    simple linear trend fit on the bin's own recent readings (still a real
    regression, just per-bin instead of global).
    recent_readings: list of dicts sorted ascending by recorded_at with
                      keys fill_level, recorded_at
    """
    model = load_overflow_model()
    now = datetime.utcnow()
    last_collected = bin_dict.get("last_collected_at") or now
    if isinstance(last_collected, str):
        last_collected = datetime.fromisoformat(last_collected)

    predictions = {}

    if model is not None:
        for h in horizon_hours:
            future_time = now + timedelta(hours=h)
            hours_since_collection = (future_time - last_collected).total_seconds() / 3600.0
            row = pd.DataFrame([{
                "hours_since_collection": max(hours_since_collection, 0),
                "weight_kg": bin_dict.get("weight_kg", 0),
                "temperature_c": bin_dict.get("temperature_c", 28),
                "bin_type_enc": BIN_TYPE_MAP.get(bin_dict.get("bin_type", "General"), 0),
                "capacity_kg": bin_dict.get("capacity_kg", 100),
                "hour_of_day": future_time.hour,
                "day_of_week": future_time.weekday(),
            }])[FEATURE_COLS]
            pred = float(model.predict(row)[0])
            predictions[f"+{h}h"] = round(min(max(pred, 0), 100), 1)
        method = "RandomForestRegressor"
    else:
        # Fallback: linear trend from the bin's own recent history
        if len(recent_readings) >= 2:
            xs = np.array([(datetime.fromisoformat(r["recorded_at"]) - now).total_seconds() / 3600.0
                           for r in recent_readings])
            ys = np.array([r["fill_level"] for r in recent_readings])
            slope, intercept = np.polyfit(xs, ys, 1)
            for h in horizon_hours:
                pred = slope * h + intercept
                predictions[f"+{h}h"] = round(float(min(max(pred, 0), 100)), 1)
        else:
            current = bin_dict.get("fill_level", 0)
            for h in horizon_hours:
                predictions[f"+{h}h"] = round(current, 1)
        method = "LinearTrend(fallback)"

    # Estimate hours until overflow threshold using linear extrapolation of predictions
    hrs = np.array(horizon_hours, dtype=float)
    vals = np.array([predictions[f"+{h}h"] for h in horizon_hours])
    time_to_overflow_hours = None
    if len(hrs) >= 2:
        slope, intercept = np.polyfit(hrs, vals, 1)
        if slope > 0.001:
            t = (OVERFLOW_THRESHOLD - intercept) / slope
            if t > 0:
                time_to_overflow_hours = round(float(t), 1)

    current_fill = bin_dict.get("fill_level", 0)
    if current_fill >= OVERFLOW_THRESHOLD:
        risk = "critical"
    elif time_to_overflow_hours is not None and time_to_overflow_hours <= 24:
        risk = "high"
    elif time_to_overflow_hours is not None and time_to_overflow_hours <= 72:
        risk = "medium"
    else:
        risk = "low"

    return {
        "bin_id": bin_dict.get("id"),
        "current_fill_level": current_fill,
        "predictions": predictions,
        "predicted_hours_to_overflow": time_to_overflow_hours,
        "risk_level": risk,
        "method": method,
    }


# ---------------------- Waste generation forecasting ----------------------

def _daily_totals_df(daily_rows):
    """daily_rows: list of dicts {area, date, total_kg}"""
    df = pd.DataFrame(daily_rows)
    if df.empty:
        return df
    df["date"] = pd.to_datetime(df["date"])
    df["day_of_week"] = df["date"].dt.dayofweek
    df["day_of_month"] = df["date"].dt.day
    df["month"] = df["date"].dt.month
    df = df.sort_values(["area", "date"])
    df["rolling_avg_7"] = df.groupby("area")["total_kg"].transform(
        lambda s: s.rolling(7, min_periods=1).mean())
    return df


def train_waste_forecast_model(daily_rows):
    df = _daily_totals_df(daily_rows)
    if len(df) < 21:
        return {"trained": False, "reason": "Not enough daily history yet (need >=21 day-records)."}

    areas = sorted(df["area"].unique().tolist())
    area_map = {a: i for i, a in enumerate(areas)}
    df["area_enc"] = df["area"].map(area_map)

    feature_cols = ["day_of_week", "day_of_month", "month", "rolling_avg_7", "area_enc"]
    X = df[feature_cols]
    y = df["total_kg"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestRegressor(n_estimators=150, max_depth=8, random_state=42)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    mae = mean_absolute_error(y_test, preds)

    joblib.dump({"model": model, "area_map": area_map}, FORECAST_MODEL_PATH)
    return {"trained": True, "mae": round(float(mae), 2), "n_samples": len(df), "areas": areas}


def forecast_waste_generation(daily_rows, days_ahead=7):
    """Forecast next `days_ahead` days of total waste (kg) per area."""
    bundle = None
    if os.path.exists(FORECAST_MODEL_PATH):
        bundle = joblib.load(FORECAST_MODEL_PATH)

    df = _daily_totals_df(daily_rows)
    if df.empty:
        return {}

    results = {}
    for area, group in df.groupby("area"):
        group = group.sort_values("date")
        last_date = group["date"].max()
        rolling_avg = group["total_kg"].tail(7).mean()

        forecasts = []
        for i in range(1, days_ahead + 1):
            future_date = last_date + timedelta(days=i)
            if bundle and area in bundle["area_map"]:
                row = pd.DataFrame([{
                    "day_of_week": future_date.dayofweek,
                    "day_of_month": future_date.day,
                    "month": future_date.month,
                    "rolling_avg_7": rolling_avg,
                    "area_enc": bundle["area_map"][area],
                }])
                pred = float(bundle["model"].predict(row)[0])
            else:
                # fallback: simple weekly-seasonal average of same weekday
                same_weekday = group[group["date"].dt.dayofweek == future_date.dayofweek]["total_kg"]
                pred = float(same_weekday.mean()) if len(same_weekday) else float(rolling_avg)
            forecasts.append({"date": future_date.date().isoformat(), "predicted_kg": round(max(pred, 0), 1)})

        results[area] = forecasts
    return results
